'use client';

import { IdeaEvaluationResponse } from '@/lib/api/aiApi';

interface IdeaEvaluatorProps {
  evaluation: IdeaEvaluationResponse;
}

export default function IdeaEvaluator({ evaluation }: IdeaEvaluatorProps) {
  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/15';
    if (score >= 60) return 'text-indigo-400 bg-indigo-500/10 border-indigo-500/15';
    if (score >= 40) return 'text-amber-400 bg-amber-500/10 border-amber-500/15';
    return 'text-rose-400 bg-rose-500/10 border-rose-500/15';
  };

  const getProgressColor = (score: number) => {
    if (score >= 80) return 'bg-emerald-500';
    if (score >= 60) return 'bg-indigo-500';
    if (score >= 40) return 'bg-amber-500';
    return 'bg-rose-500';
  };

  return (
    <div className="space-y-8 animate-fade-in text-left">
      {/* Overview Block */}
      <div className="glass-card p-6 border border-white/5 bg-white/[0.02] flex flex-col md:flex-row justify-between items-center gap-6">
        <div className="space-y-2 max-w-xl">
          <h3 className="text-xl font-bold text-white">AI Evaluation Scorecard</h3>
          <p className="text-gray-400 text-sm leading-relaxed">
            This scorecard is automatically generated by parsing the project description against market innovation, technical feasibility, and student group workloads.
          </p>
        </div>
        <div className="shrink-0 text-center">
          <div className={`w-24 h-24 rounded-full flex flex-col items-center justify-center border ${getScoreColor(evaluation.overall_score)} shadow-lg shadow-indigo-500/5`}>
            <span className="text-3xl font-extrabold">{evaluation.overall_score}</span>
            <span className="text-[10px] uppercase font-bold tracking-wider opacity-80">Overall</span>
          </div>
        </div>
      </div>

      {/* Metrics breakdown */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Feasibility */}
        <div className="glass-card p-6 border border-white/5 bg-white/[0.01]">
          <div className="flex justify-between items-center mb-3">
            <span className="text-sm font-bold text-gray-300">Feasibility</span>
            <span className={`px-2 py-0.5 rounded text-xs font-bold ${getScoreColor(evaluation.feasibility_score)}`}>
              {evaluation.feasibility_score}/100
            </span>
          </div>
          <div className="w-full h-1.5 bg-white/5 rounded-full mb-4 overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-500 ${getProgressColor(evaluation.feasibility_score)}`}
              style={{ width: `${evaluation.feasibility_score}%` }}
            />
          </div>
          <p className="text-gray-400 text-xs leading-relaxed">{evaluation.feasibility_rationale}</p>
        </div>

        {/* Innovation */}
        <div className="glass-card p-6 border border-white/5 bg-white/[0.01]">
          <div className="flex justify-between items-center mb-3">
            <span className="text-sm font-bold text-gray-300">Innovation</span>
            <span className={`px-2 py-0.5 rounded text-xs font-bold ${getScoreColor(evaluation.innovation_score)}`}>
              {evaluation.innovation_score}/100
            </span>
          </div>
          <div className="w-full h-1.5 bg-white/5 rounded-full mb-4 overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-500 ${getProgressColor(evaluation.innovation_score)}`}
              style={{ width: `${evaluation.innovation_score}%` }}
            />
          </div>
          <p className="text-gray-400 text-xs leading-relaxed">{evaluation.innovation_rationale}</p>
        </div>

        {/* Impact */}
        <div className="glass-card p-6 border border-white/5 bg-white/[0.01]">
          <div className="flex justify-between items-center mb-3">
            <span className="text-sm font-bold text-gray-300">Impact</span>
            <span className={`px-2 py-0.5 rounded text-xs font-bold ${getScoreColor(evaluation.impact_score)}`}>
              {evaluation.impact_score}/100
            </span>
          </div>
          <div className="w-full h-1.5 bg-white/5 rounded-full mb-4 overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-500 ${getProgressColor(evaluation.impact_score)}`}
              style={{ width: `${evaluation.impact_score}%` }}
            />
          </div>
          <p className="text-gray-400 text-xs leading-relaxed">{evaluation.impact_rationale}</p>
        </div>
      </div>

      {/* Strengths & Weaknesses Columns */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <div className="glass-card p-6 border border-emerald-500/10 bg-emerald-500/[0.01] space-y-4">
          <h4 className="text-emerald-400 font-bold text-sm flex items-center gap-2">
            <span>🟢</span> Key Strengths
          </h4>
          <ul className="space-y-2.5 text-xs text-gray-300">
            {evaluation.strengths.map((str, i) => (
              <li key={i} className="flex gap-2 items-start">
                <span className="text-emerald-500 shrink-0">✓</span>
                <span className="leading-relaxed">{str}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Weaknesses */}
        <div className="glass-card p-6 border border-rose-500/10 bg-rose-500/[0.01] space-y-4">
          <h4 className="text-rose-400 font-bold text-sm flex items-center gap-2">
            <span>🔴</span> Risks & Weaknesses
          </h4>
          <ul className="space-y-2.5 text-xs text-gray-300">
            {evaluation.weaknesses.map((weak, i) => (
              <li key={i} className="flex gap-2 items-start">
                <span className="text-rose-500 shrink-0">!</span>
                <span className="leading-relaxed">{weak}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Recommended Tech Stack & Action Tips */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Suggested Tech Stack */}
        <div className="glass-card p-6 border border-white/5 bg-white/[0.01] md:col-span-1 space-y-4">
          <h4 className="text-white font-bold text-sm">Suggested Stack</h4>
          <div className="flex flex-wrap gap-2">
            {evaluation.suggested_tech_stack.map((tech) => (
              <span
                key={tech}
                className="px-2.5 py-1 rounded-md text-[10px] font-semibold bg-white/5 border border-white/10 text-gray-300"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>

        {/* Recommendations */}
        <div className="glass-card p-6 border border-white/5 bg-white/[0.01] md:col-span-2 space-y-4">
          <h4 className="text-white font-bold text-sm">Actionable Recommendations</h4>
          <ul className="space-y-3 text-xs text-gray-300">
            {evaluation.recommendations.map((rec, i) => (
              <li key={i} className="flex gap-3 items-start">
                <span className="w-5 h-5 rounded bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 flex items-center justify-center shrink-0 font-bold text-[10px]">
                  {i + 1}
                </span>
                <span className="leading-relaxed mt-0.5">{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
